# Generated by Django 5.2.9 on 2025-12-12 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='extracteddata',
            old_name='data',
            new_name='raw_extraction',
        ),
        migrations.RenameField(
            model_name='reviewtask',
            old_name='completed_at',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='extracteddata',
            name='raw_model_response',
        ),
        migrations.AddField(
            model_name='document',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='field_confidences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='overall_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reviewtask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('requires_review', 'Requires Review'), ('approved', 'Approved'), ('processed', 'Processed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='CorrectionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrected_fields', models.JSONField(default=dict)),
                ('raw_extraction', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_examples', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
