# Generated by Django 5.2.17 on 2026-10-03 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_rename_data_extracteddata_raw_extraction_and_more"),
        ("organizations", "0004_organization_auto_approve_max_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="page_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_task_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="dedupe_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=400
            ),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="purchase_order",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="tax_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="validation",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("requires_review", "Requires Review"),
                    ("approved", "Approved"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="extracteddata",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="documents_d_organiz_1663e1_idx",
            ),
        ),
    ]
