# Generated by Django 5.2.17 on 2026-10-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_pipeline_v2"),
        ("organizations", "0006_organization_other_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddata",
            name="vendor_tax_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("name_key", models.CharField(max_length=255)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("tax_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "default_currency",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="documents.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["organization", "tax_id"], name="documents_v_organiz_80132f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=("organization", "name_key"), name="vendor_unique_name_per_org"
            ),
        ),
    ]
