# Generated by Django 5.2.17 on 2026-10-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_vendors"),
    ]

    operations = [
        migrations.AddField(
            model_name="extracteddata",
            name="amount_due",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="bank_account",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="extracteddata",
            name="bank_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bank_account",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bank_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
