# Generated by Django 5.2.17 on 2026-10-04 01:13

import apps.documents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookconfig",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="webhookconfig",
            name="events",
            field=models.JSONField(
                blank=True, default=apps.documents.models._all_events
            ),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="event_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="event_type",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="response_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="webhookdeliverylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="webhookconfig",
            name="target_url",
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name="webhookdeliverylog",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_delivery_logs",
                to="documents.document",
            ),
        ),
    ]
