# Generated by Django 5.2.17 on 2026-10-04 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_webhooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="proposed_bank_account",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="vendor",
            name="proposed_bank_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="vendor",
            name="proposed_bank_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.document",
            ),
        ),
    ]
