# Generated by Django 5.2.9 on 2025-12-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_approve_threshold',
            field=models.FloatField(default=0.92, help_text='Overall confidence threshold to auto-approve without human review'),
        ),
    ]
