# Generated by Django 5.2.17 on 2026-10-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_auto_approve_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="auto_approve_max_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Invoices with a total above this amount always go to human review. Empty = no limit.",
                max_digits=14,
                null=True,
            ),
        ),
    ]
