# Generated by Django 5.2.17 on 2026-10-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organization_auto_approve_max_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="review_new_vendors",
            field=models.BooleanField(
                default=False,
                help_text="Send the first invoice from each new vendor to human review.",
            ),
        ),
    ]
