# Generated by Django 5.2.17 on 2026-10-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_organization_review_new_vendors"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="other_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Other names the company uses on invoices (trade names, old names). Used to spot invoices where the customer was read as the vendor.",
            ),
        ),
    ]
